---
name: Register TRE Bundles

# This workflow registers all TRE bundles into an existing TRE environment

on:
  push:
    branches:
      - guybartal/publish-bundle-workflow
  workflow_dispatch:
    inputs:
      environment:
        description: The name of the Github Action's environment this will deploy into
        type: string
        default: CICD
        required: false

jobs:
  call-register-bundle:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    strategy:
      matrix:
        bundle_type:
          - workspace
          - unrestricted
          - airlock-import-review
          - guacamole
          - azureml
          - gitea
          - mysql
          - health-services
          - databricks
          - ohdsi
          - azuresql
          - openai
          - guacamole-azure-windowsvm
          - guacamole-azure-linuxvm
          - guacamole-azure-export-reviewvm
          - guacamole-azure-import-reviewvm
    uses: ./.github/workflows/register_tre_bundle.yml
    with:
      bundle_type: ${{ matrix.bundle_type }}
